import About from "@/components/about";
import ContactSection from "@/components/contact";
import ContinuousSlider from "@/components/continuousSlider";
import HeroSection from "@/components/heroSection";
import Investment from "@/components/investment";
import Offer from "@/components/offer";
import Partner from "@/components/partner";
import Projects from "@/components/projects";
import Testimonials from "@/components/testimonials";
import { BannerData } from "@/utils/bannerData";
import { data } from "@/utils/data";
import { Box } from "@mui/material";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Box>
        <HeroSection data={BannerData} />
        <Box sx={{ pt: 10 }}>
          <About
            heading1="Welcome to Prefinn"
            coloredHeading="Your Trusted Finance & Fintech Solution Partner"
            heading2="Partner"
            description="Prefinn is a Fintech Solution Partner firm specializing in finance and fintech, founded by expert banking professionals with extensive experience in areas such as:"
            list={data.list1}
            description2="Our firm aims to bridge the gap between traditional financial institutions and innovative fintech solutions, thereby enhancing operational efficiency and profitability for its clients."
          />
        </Box>
        <Box sx={{ pt: 10, pb: 10 }}>
          <Offer />
        </Box>
        <Box sx={{ pt: 10, pb: 10 }}>
          <Investment />
        </Box>
        <Box sx={{ pt: 10, pb: 10 }}>
          <Projects />
        </Box>
        <Box sx={{ pb: 10 }}>
          <ContinuousSlider />
        </Box>
        <Box sx={{ pb: 10 }}>
          <Testimonials />
        </Box>
        <Box sx={{ pb: 10 }}>
          <Partner />
        </Box>
        <Box sx={{ pb: 10 }}>
          <ContactSection />
        </Box>
      </Box>
    </>
  );
}
