export enum SERVICESTABS {
  FINTECH_SOLUTIONS = "PROJECT MANAGEMENT",
  FINANCE_MANAGEMENT_SERVICES = "FINANCE MANAGEMENT",
  FINTECH_CONSULTANCY = "FINTECH CONSULTANCY",
  RBI_TRAINING_CERTIFICATIONS = "TRAINING AND CERTIFICATIONS",
}
