export enum SERVICESTABS {
  FINTECH_SOLUTIONS = "FINTECH SOLUTIONS",
  FINANCE_MANAGEMENT_SERVICES = "FINANCE MANAGEMENT SERVICES",
  FINTECH_CONSULTANCY = "FINTECH CONSULTANCY",
  RBI_TRAINING_CERTIFICATIONS = "RBI TRAINING & CERTIFICATIONS",
}
