export enum SERVICESTABS {
  FINTECH_SOLUTIONS = "PROJECT MANAGEMENT",
  FINANCE_MANAGEMENT_SERVICES = "FINANCE MANAGEMENT",
  FINTECH_CONSULTANCY = "FINTECH CONSULTANCY",
  RBI_TRAINING_CERTIFICATIONS = "TRAINING AND CERTIFICATIONS",
}

export enum EMAILJS_CREDIENTIALS {
  SERVICE_ID = "service_0gtr38c",
  TEMPLATE_ID = "template_27lotbr",
  PUBLIC_KEY = "XXBIRod9xkGtLWUZp",
  PARTNER_TEMPLATE = "template_h4df5gg",
}
